//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;

namespace Research.Services.Northwind.NorthwindDataSetRepositories
{

	public partial interface ICategoryRepository
	{
		System.Int32 Fill(Research.DataAccess.Northwind.NorthwindDataSet.CategoryDataTable dataTable);
		Research.DataAccess.Northwind.NorthwindDataSet.CategoryDataTable GetAll();
		System.Int32 FillById(Research.DataAccess.Northwind.NorthwindDataSet.CategoryDataTable dataTable,System.Int32 CategoryID);
		Research.DataAccess.Northwind.NorthwindDataSet.CategoryDataTable GetById(System.Int32 CategoryID);
	}


	public partial interface ICustomerRepository
	{
		System.Int32 Fill(Research.DataAccess.Northwind.NorthwindDataSet.CustomerDataTable dataTable);
		Research.DataAccess.Northwind.NorthwindDataSet.CustomerDataTable GetAll();
		System.Int32 FillById(Research.DataAccess.Northwind.NorthwindDataSet.CustomerDataTable dataTable,System.String CustomerID);
		Research.DataAccess.Northwind.NorthwindDataSet.CustomerDataTable GetById(System.String CustomerID);
	}


	public partial interface IEmployeeRepository
	{
		System.Int32 Fill(Research.DataAccess.Northwind.NorthwindDataSet.EmployeeDataTable dataTable);
		Research.DataAccess.Northwind.NorthwindDataSet.EmployeeDataTable GetAll();
		System.Int32 FillById(Research.DataAccess.Northwind.NorthwindDataSet.EmployeeDataTable dataTable,System.Int32 EmployeeID);
		Research.DataAccess.Northwind.NorthwindDataSet.EmployeeDataTable GetById(System.Int32 EmployeeID);
	}


	public partial interface IOrderDetailRepository
	{
		System.Int32 Fill(Research.DataAccess.Northwind.NorthwindDataSet.OrderDetailDataTable dataTable);
		Research.DataAccess.Northwind.NorthwindDataSet.OrderDetailDataTable GetAll();
		System.Int32 FillById(Research.DataAccess.Northwind.NorthwindDataSet.OrderDetailDataTable dataTable,System.Int32 OrderID);
		Research.DataAccess.Northwind.NorthwindDataSet.OrderDetailDataTable GetById(System.Int32 OrderID);
	}


	public partial interface IOrderRepository
	{
		System.Int32 Fill(Research.DataAccess.Northwind.NorthwindDataSet.OrderDataTable dataTable);
		Research.DataAccess.Northwind.NorthwindDataSet.OrderDataTable GetAll();
		System.Int32 FillById(Research.DataAccess.Northwind.NorthwindDataSet.OrderDataTable dataTable,System.Int32 OrderID);
		Research.DataAccess.Northwind.NorthwindDataSet.OrderDataTable GetById(System.Int32 OrderID);
	}


	public partial interface IProductRepository
	{
		System.Int32 Fill(Research.DataAccess.Northwind.NorthwindDataSet.ProductDataTable dataTable);
		Research.DataAccess.Northwind.NorthwindDataSet.ProductDataTable GetAll();
		System.Int32 FillById(Research.DataAccess.Northwind.NorthwindDataSet.ProductDataTable dataTable,System.Int32 ProductID);
		Research.DataAccess.Northwind.NorthwindDataSet.ProductDataTable GetById(System.Int32 ProductID);
	}


	public partial interface IShipperRepository
	{
		System.Int32 Fill(Research.DataAccess.Northwind.NorthwindDataSet.ShipperDataTable dataTable);
		Research.DataAccess.Northwind.NorthwindDataSet.ShipperDataTable GetAll();
		System.Int32 FillById(Research.DataAccess.Northwind.NorthwindDataSet.ShipperDataTable dataTable,System.Int32 ShipperID);
		Research.DataAccess.Northwind.NorthwindDataSet.ShipperDataTable GetById(System.Int32 ShipperID);
	}


	public partial interface ISupplierRepository
	{
		System.Int32 Fill(Research.DataAccess.Northwind.NorthwindDataSet.SupplierDataTable dataTable);
		Research.DataAccess.Northwind.NorthwindDataSet.SupplierDataTable GetAll();
		System.Int32 FillById(Research.DataAccess.Northwind.NorthwindDataSet.SupplierDataTable dataTable,System.Int32 SupplierID);
		Research.DataAccess.Northwind.NorthwindDataSet.SupplierDataTable GetById(System.Int32 SupplierID);
	}



	public partial class CategoryRepository :
		Research.Services.Northwind.NorthwindDataSetRepositories.ICategoryRepository
	{
		private Research.DataAccess.Northwind.NorthwindDataSetTableAdapters.CategoryTableAdapter m_Adapter = null;

		public CategoryRepository() { }

		public CategoryRepository(Research.DataAccess.Northwind.NorthwindDataSetTableAdapters.CategoryTableAdapter adapter)
		{
			m_Adapter = adapter;
		}

		public System.Int32 Fill(Research.DataAccess.Northwind.NorthwindDataSet.CategoryDataTable dataTable)
		{
			return m_Adapter.Fill(dataTable);
		}

		public Research.DataAccess.Northwind.NorthwindDataSet.CategoryDataTable GetAll()
		{
			return m_Adapter.GetAll();
		}

		public System.Int32 FillById(Research.DataAccess.Northwind.NorthwindDataSet.CategoryDataTable dataTable,System.Int32 CategoryID)
		{
			return m_Adapter.FillById(dataTable,CategoryID);
		}

		public Research.DataAccess.Northwind.NorthwindDataSet.CategoryDataTable GetById(System.Int32 CategoryID)
		{
			return m_Adapter.GetById(CategoryID);
		}

		private Research.DataAccess.Northwind.NorthwindDataSetTableAdapters.CategoryTableAdapter Adapter
		{
			get
			{
				return m_Adapter;
			}
		}
	}


	public partial class CustomerRepository :
		Research.Services.Northwind.NorthwindDataSetRepositories.ICustomerRepository
	{
		private Research.DataAccess.Northwind.NorthwindDataSetTableAdapters.CustomerTableAdapter m_Adapter = null;

		public CustomerRepository() { }

		public CustomerRepository(Research.DataAccess.Northwind.NorthwindDataSetTableAdapters.CustomerTableAdapter adapter)
		{
			m_Adapter = adapter;
		}

		public System.Int32 Fill(Research.DataAccess.Northwind.NorthwindDataSet.CustomerDataTable dataTable)
		{
			return m_Adapter.Fill(dataTable);
		}

		public Research.DataAccess.Northwind.NorthwindDataSet.CustomerDataTable GetAll()
		{
			return m_Adapter.GetAll();
		}

		public System.Int32 FillById(Research.DataAccess.Northwind.NorthwindDataSet.CustomerDataTable dataTable,System.String CustomerID)
		{
			return m_Adapter.FillById(dataTable,CustomerID);
		}

		public Research.DataAccess.Northwind.NorthwindDataSet.CustomerDataTable GetById(System.String CustomerID)
		{
			return m_Adapter.GetById(CustomerID);
		}

		private Research.DataAccess.Northwind.NorthwindDataSetTableAdapters.CustomerTableAdapter Adapter
		{
			get
			{
				return m_Adapter;
			}
		}
	}


	public partial class EmployeeRepository :
		Research.Services.Northwind.NorthwindDataSetRepositories.IEmployeeRepository
	{
		private Research.DataAccess.Northwind.NorthwindDataSetTableAdapters.EmployeeTableAdapter m_Adapter = null;

		public EmployeeRepository() { }

		public EmployeeRepository(Research.DataAccess.Northwind.NorthwindDataSetTableAdapters.EmployeeTableAdapter adapter)
		{
			m_Adapter = adapter;
		}

		public System.Int32 Fill(Research.DataAccess.Northwind.NorthwindDataSet.EmployeeDataTable dataTable)
		{
			return m_Adapter.Fill(dataTable);
		}

		public Research.DataAccess.Northwind.NorthwindDataSet.EmployeeDataTable GetAll()
		{
			return m_Adapter.GetAll();
		}

		public System.Int32 FillById(Research.DataAccess.Northwind.NorthwindDataSet.EmployeeDataTable dataTable,System.Int32 EmployeeID)
		{
			return m_Adapter.FillById(dataTable,EmployeeID);
		}

		public Research.DataAccess.Northwind.NorthwindDataSet.EmployeeDataTable GetById(System.Int32 EmployeeID)
		{
			return m_Adapter.GetById(EmployeeID);
		}

		private Research.DataAccess.Northwind.NorthwindDataSetTableAdapters.EmployeeTableAdapter Adapter
		{
			get
			{
				return m_Adapter;
			}
		}
	}


	public partial class OrderDetailRepository :
		Research.Services.Northwind.NorthwindDataSetRepositories.IOrderDetailRepository
	{
		private Research.DataAccess.Northwind.NorthwindDataSetTableAdapters.OrderDetailTableAdapter m_Adapter = null;

		public OrderDetailRepository() { }

		public OrderDetailRepository(Research.DataAccess.Northwind.NorthwindDataSetTableAdapters.OrderDetailTableAdapter adapter)
		{
			m_Adapter = adapter;
		}

		public System.Int32 Fill(Research.DataAccess.Northwind.NorthwindDataSet.OrderDetailDataTable dataTable)
		{
			return m_Adapter.Fill(dataTable);
		}

		public Research.DataAccess.Northwind.NorthwindDataSet.OrderDetailDataTable GetAll()
		{
			return m_Adapter.GetAll();
		}

		public System.Int32 FillById(Research.DataAccess.Northwind.NorthwindDataSet.OrderDetailDataTable dataTable,System.Int32 OrderID)
		{
			return m_Adapter.FillById(dataTable,OrderID);
		}

		public Research.DataAccess.Northwind.NorthwindDataSet.OrderDetailDataTable GetById(System.Int32 OrderID)
		{
			return m_Adapter.GetById(OrderID);
		}

		private Research.DataAccess.Northwind.NorthwindDataSetTableAdapters.OrderDetailTableAdapter Adapter
		{
			get
			{
				return m_Adapter;
			}
		}
	}


	public partial class OrderRepository :
		Research.Services.Northwind.NorthwindDataSetRepositories.IOrderRepository
	{
		private Research.DataAccess.Northwind.NorthwindDataSetTableAdapters.OrderTableAdapter m_Adapter = null;

		public OrderRepository() { }

		public OrderRepository(Research.DataAccess.Northwind.NorthwindDataSetTableAdapters.OrderTableAdapter adapter)
		{
			m_Adapter = adapter;
		}

		public System.Int32 Fill(Research.DataAccess.Northwind.NorthwindDataSet.OrderDataTable dataTable)
		{
			return m_Adapter.Fill(dataTable);
		}

		public Research.DataAccess.Northwind.NorthwindDataSet.OrderDataTable GetAll()
		{
			return m_Adapter.GetAll();
		}

		public System.Int32 FillById(Research.DataAccess.Northwind.NorthwindDataSet.OrderDataTable dataTable,System.Int32 OrderID)
		{
			return m_Adapter.FillById(dataTable,OrderID);
		}

		public Research.DataAccess.Northwind.NorthwindDataSet.OrderDataTable GetById(System.Int32 OrderID)
		{
			return m_Adapter.GetById(OrderID);
		}

		private Research.DataAccess.Northwind.NorthwindDataSetTableAdapters.OrderTableAdapter Adapter
		{
			get
			{
				return m_Adapter;
			}
		}
	}


	public partial class ProductRepository :
		Research.Services.Northwind.NorthwindDataSetRepositories.IProductRepository
	{
		private Research.DataAccess.Northwind.NorthwindDataSetTableAdapters.ProductTableAdapter m_Adapter = null;

		public ProductRepository() { }

		public ProductRepository(Research.DataAccess.Northwind.NorthwindDataSetTableAdapters.ProductTableAdapter adapter)
		{
			m_Adapter = adapter;
		}

		public System.Int32 Fill(Research.DataAccess.Northwind.NorthwindDataSet.ProductDataTable dataTable)
		{
			return m_Adapter.Fill(dataTable);
		}

		public Research.DataAccess.Northwind.NorthwindDataSet.ProductDataTable GetAll()
		{
			return m_Adapter.GetAll();
		}

		public System.Int32 FillById(Research.DataAccess.Northwind.NorthwindDataSet.ProductDataTable dataTable,System.Int32 ProductID)
		{
			return m_Adapter.FillById(dataTable,ProductID);
		}

		public Research.DataAccess.Northwind.NorthwindDataSet.ProductDataTable GetById(System.Int32 ProductID)
		{
			return m_Adapter.GetById(ProductID);
		}

		private Research.DataAccess.Northwind.NorthwindDataSetTableAdapters.ProductTableAdapter Adapter
		{
			get
			{
				return m_Adapter;
			}
		}
	}


	public partial class ShipperRepository :
		Research.Services.Northwind.NorthwindDataSetRepositories.IShipperRepository
	{
		private Research.DataAccess.Northwind.NorthwindDataSetTableAdapters.ShipperTableAdapter m_Adapter = null;

		public ShipperRepository() { }

		public ShipperRepository(Research.DataAccess.Northwind.NorthwindDataSetTableAdapters.ShipperTableAdapter adapter)
		{
			m_Adapter = adapter;
		}

		public System.Int32 Fill(Research.DataAccess.Northwind.NorthwindDataSet.ShipperDataTable dataTable)
		{
			return m_Adapter.Fill(dataTable);
		}

		public Research.DataAccess.Northwind.NorthwindDataSet.ShipperDataTable GetAll()
		{
			return m_Adapter.GetAll();
		}

		public System.Int32 FillById(Research.DataAccess.Northwind.NorthwindDataSet.ShipperDataTable dataTable,System.Int32 ShipperID)
		{
			return m_Adapter.FillById(dataTable,ShipperID);
		}

		public Research.DataAccess.Northwind.NorthwindDataSet.ShipperDataTable GetById(System.Int32 ShipperID)
		{
			return m_Adapter.GetById(ShipperID);
		}

		private Research.DataAccess.Northwind.NorthwindDataSetTableAdapters.ShipperTableAdapter Adapter
		{
			get
			{
				return m_Adapter;
			}
		}
	}


	public partial class SupplierRepository :
		Research.Services.Northwind.NorthwindDataSetRepositories.ISupplierRepository
	{
		private Research.DataAccess.Northwind.NorthwindDataSetTableAdapters.SupplierTableAdapter m_Adapter = null;

		public SupplierRepository() { }

		public SupplierRepository(Research.DataAccess.Northwind.NorthwindDataSetTableAdapters.SupplierTableAdapter adapter)
		{
			m_Adapter = adapter;
		}

		public System.Int32 Fill(Research.DataAccess.Northwind.NorthwindDataSet.SupplierDataTable dataTable)
		{
			return m_Adapter.Fill(dataTable);
		}

		public Research.DataAccess.Northwind.NorthwindDataSet.SupplierDataTable GetAll()
		{
			return m_Adapter.GetAll();
		}

		public System.Int32 FillById(Research.DataAccess.Northwind.NorthwindDataSet.SupplierDataTable dataTable,System.Int32 SupplierID)
		{
			return m_Adapter.FillById(dataTable,SupplierID);
		}

		public Research.DataAccess.Northwind.NorthwindDataSet.SupplierDataTable GetById(System.Int32 SupplierID)
		{
			return m_Adapter.GetById(SupplierID);
		}

		private Research.DataAccess.Northwind.NorthwindDataSetTableAdapters.SupplierTableAdapter Adapter
		{
			get
			{
				return m_Adapter;
			}
		}
	}

}